# Generated by Django 4.2.13 on 2026-05-28 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone string, e.g. Asia/Kolkata', max_length=64)),
                ('date_display_format', models.CharField(default='YYYY-MM-DD', help_text='UI date format token string, e.g. DD/MM/YYYY', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
