# Generated by Django 4.2.13 on 2026-05-28 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('ingestion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='scope_2', max_length=20)),
                ('schema_type', models.CharField(default='standard', max_length=50)),
                ('activity_date', models.DateField()),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(default='kWh', max_length=50)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_approvals', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='records.utilityrecord')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_edits', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_records', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='scope_3', max_length=20)),
                ('travel_type', models.CharField(choices=[('air', 'Air'), ('hotel', 'Hotel'), ('car', 'Car'), ('rail', 'Rail')], max_length=20)),
                ('schema_type', models.CharField(default='travel_csv', max_length=50)),
                ('activity_date', models.DateField()),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_approvals', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='records.travelrecord')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_edits', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='SapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='scope_1', max_length=20)),
                ('schema_type', models.CharField(default='sap_csv', max_length=50)),
                ('source_type', models.CharField(default='sap_procurement', max_length=30)),
                ('activity_date', models.DateField()),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(default='kg CO2e', max_length=50)),
                ('description', models.TextField(default='')),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_approvals', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='records.saprecord')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_edits', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_records', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
    ]
